<?php

namespace Drupal\webform;

use Drupal\webprofiler\Entity\ConfigEntityStorageDecorator;
use Drupal\Component\Render\FormattableMarkup;
use Drupal\Component\Serialization\Yaml;
use Drupal\Core\Config\Entity\ConfigEntityStorage;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\webform\Element\WebformCompositeBase;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * This file is auto-generated by the Webprofiler module.
 */
class WebformOptionsStorageDecorator extends ConfigEntityStorageDecorator implements \Drupal\webform\WebformOptionsStorageInterface
{
    public function getCategories()
    {
        return $this->getOriginalObject()->getCategories();
    }
    public function getOptions()
    {
        return $this->getOriginalObject()->getOptions();
    }
    public function getLikerts()
    {
        return $this->getOriginalObject()->getLikerts();
    }
    public function getUsedByCompositeElements(WebformOptionsInterface $webform_options)
    {
        return $this->getOriginalObject()->getUsedByCompositeElements($webform_options);
    }
    public function getUsedByWebforms(WebformOptionsInterface $webform_options)
    {
        return $this->getOriginalObject()->getUsedByWebforms($webform_options);
    }
}
