<?php

declare(strict_types=1);

/**
 * This removes the default cookies response that bypasses message queue,
 * making it difficult to style like regular messages
 *
 * @param bool $consent
 *
 * @return array
 */
function cookies_consent_cookies_user_consent(bool $consent): array
{
    $account = Drupal::currentUser();

    if (!$account->isAuthenticated()) {
        return [];
    }

    $key = 'uid:' . $account->id();

    Drupal::keyValue('cookies.consent.user')->set($key, $consent);

    return [];
}
