<?php

namespace Drupal\taxonomy;

use Drupal\webprofiler\Entity\ConfigEntityStorageDecorator;
use Drupal\Core\Config\Entity\ConfigEntityStorage;

/**
 * This file is auto-generated by the Webprofiler module.
 */
class VocabularyStorageDecorator extends ConfigEntityStorageDecorator implements \Drupal\taxonomy\VocabularyStorageInterface
{
    public function getToplevelTids($vids)
    {
        return $this->getOriginalObject()->getToplevelTids($vids);
    }
}
