_core:
  default_config_hash: cd8_DBKdTaJPQesJJM8CEbPA744-Uc-0lOqnotq28PE
langcode: en
cookie_name: cookiesjsr
cookie_expires: 365
cookie_domain: ''
cookie_secure: true
cookie_same_site: Lax
open_settings_hash: editCookieSettings
show_deny_all: false
deny_all_on_layer_close: false
settings_as_link: false
group_consent: false
cookie_docs: false
lib_load_from_cdn: true
lib_scroll_limit: 0
use_default_styles: false
store_auth_user_consent: false
