_core:
  default_config_hash: HhNyhQ6tRke0JqjC9BExmWr-cTRPJWrIlD9LXhe-8Dk
langcode: en
dialog_mode: manager
auto_decorate_final_html: false
auto_decorate_js_alter: true
auto_decorate_page_attachments: true
auto_decorate_preprocess_field: true
get_entity_thumbnail: true
block_unknown: false
log_unknown_resources: true
block_unknown_label: 'Unknown services'
block_unknown_description: 'Allow loading of unknown external resources'
show_toggle_button: false
show_close_button: true
deletable_cookie_domains: {  }
exclude_urls: {  }
disable_urls: {  }
styles:
  - light
process_descriptions: true
override_css: true
show_notice_title: false
library:
  element_id: klaro
  storage_method: cookie
  cookie_name: klaro
  cookie_expires_after_days: 180
  cookie_domain: ''
  group_by_purpose: true
  accept_all: true
  hide_decline_all: false
  hide_learn_more: false
  learn_more_as_button: true
  additional_class: ''
  html_texts: false
  auto_focus: true
