_core:
  default_config_hash: C6AdZBCR0WnfPK8ujj1079pWqBsd2gyKa2rQQHBfCe4
exclude_paths: "/contextual/*\r\n/toolbar/*\r\n/edit/*\r\n*.js\r\n*.css"
exclude_toolbar: /media/oembed
intercept_redirects: false
purge_on_cache_clear: true
active_toolbar_items:
  ajax: ajax
  blocks: blocks
  database: database
  devel: devel
  forms: forms
  memory: memory
  request: request
  time: time
  user: user
  views: views
query_sort: source
query_highlight: 5
query_detailed_output_threshold: 1000
ide: 'phpstorm://open?file=%f&line=%l'
ide_remote_path: ''
ide_local_path: ''
