<?php

namespace Drupal\user;

use Drupal\webprofiler\Entity\ConfigEntityStorageDecorator;
use Drupal\Core\Config\Entity\ConfigEntityStorage;

/**
 * This file is auto-generated by the Webprofiler module.
 */
class RoleStorageDecorator extends ConfigEntityStorageDecorator implements \Drupal\user\RoleStorageInterface
{
    public function isPermissionInRoles($permission, array $rids)
    {
        return $this->getOriginalObject()->isPermissionInRoles($permission, $rids);
    }
}
