<?php

namespace Drupal\image;

use Drupal\webprofiler\Entity\ConfigEntityStorageDecorator;
use Drupal\Core\Config\Entity\ConfigEntityStorage;

/**
 * This file is auto-generated by the Webprofiler module.
 */
class ImageStyleStorageDecorator extends ConfigEntityStorageDecorator implements \Drupal\image\ImageStyleStorageInterface
{
    public function setReplacementId($name, $replacement)
    {
        return $this->getOriginalObject()->setReplacementId($name, $replacement);
    }
    public function getReplacementId($name)
    {
        return $this->getOriginalObject()->getReplacementId($name);
    }
    public function clearReplacementId($name)
    {
        return $this->getOriginalObject()->clearReplacementId($name);
    }
}
