<?php

namespace Drupal\webform;

use Drupal\webprofiler\Entity\ConfigEntityStorageDecorator;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Config\Entity\ConfigEntityStorage;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\StreamWrapper\StreamWrapperInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * This file is auto-generated by the Webprofiler module.
 */
class WebformEntityStorageDecorator extends ConfigEntityStorageDecorator implements \Drupal\webform\WebformEntityStorageInterface
{
    public function getWebformIds()
    {
        return $this->getOriginalObject()->getWebformIds();
    }
    public function getCategories($template = NULL, $default = FALSE)
    {
        return $this->getOriginalObject()->getCategories($template, $default);
    }
    public function resetCategoriesCache()
    {
        return $this->getOriginalObject()->resetCategoriesCache();
    }
    public function getOptions($template = NULL)
    {
        return $this->getOriginalObject()->getOptions($template);
    }
    public function getNextSerial(WebformInterface $webform)
    {
        return $this->getOriginalObject()->getNextSerial($webform);
    }
    public function setNextSerial(WebformInterface $webform, $next_serial)
    {
        return $this->getOriginalObject()->setNextSerial($webform, $next_serial);
    }
    public function getSerial(WebformInterface $webform)
    {
        return $this->getOriginalObject()->getSerial($webform);
    }
    public function getMaxSerial(WebformInterface $webform)
    {
        return $this->getOriginalObject()->getMaxSerial($webform);
    }
    public function getTotalNumberOfResults($webform_id = NULL)
    {
        return $this->getOriginalObject()->getTotalNumberOfResults($webform_id);
    }
}
